### ISSUE TITLE
enable single_nat_gateway=true

### ISSUE THREAD

**Issue by hullsean** [azavea/terraform-aws-vpc#16]
I try to set this variable to true, and terraform complains.

`Error: module "dev-vpc": "single_nat_gateway" is not a valid argument`

Thoughts?

`module "dev-vpc" {
  source = "github.com/azavea/terraform-aws-vpc"

  name = "sean"
  region = "us-east-1"
  key_name = "seanone"
  cidr_block = "10.0.0.0/16"
  external_access_cidr_block = "0.0.0.0/0"
  private_subnet_cidr_blocks = ["10.0.1.0/24", "10.0.3.0/24"]
  public_subnet_cidr_blocks = ["10.0.0.0/24", "10.0.2.0/24"]
  availability_zones = ["us-east-1a", "us-east-1b"]
  bastion_ami = "ami-976152f2"
  bastion_instance_type = "t2.micro"

  project = "abc"
  environment = "dev"
  single_nat_gateway = "true"
}
`

**Comment by hectcastro** [comment]
Hey @hullsean, it doesn't look like that variable exists in our version of this module. Perhaps you are using another open source AWS VPC module.

See: https://github.com/azavea/terraform-aws-vpc/blob/develop/variables.tf

**Comment by hullsean** [comment]
Thx Hector.  Perhaps yours is a fork of the community terraform vpc?  Bc i see it's available in that parent project.  I got mixed up.  :)

Thank you.
