### ISSUE TITLE
ok to set external_nat_ip_ids?

### ISSUE THREAD

**Issue by hullsean** [azavea/terraform-aws-vpc#17]
I see this referenced in the variables.tf file.

However when I try to set it, i get a terraform error.

`Error: module "dev-vpc": "external_nat_ip_ids" is not a valid argument`

Do I have to fork the repo to configure these vars?

I also don't see it in the variables section of the README file.

Thoughts?

**Comment by hectcastro** [comment]
Simliar answer here. This variable does not exist in our VPC module.

**Comment by hullsean** [comment]
Thx Hector.  i see it's available in that parent project.  I got mixed up.  :)

Thank you.
